baseURL = '/'
languageCode = 'en-us'
title = 'Job Board'

[params]
  description = 'A job board featuring opportunities for Mandarin and Cantonese speaking professionals in the UK'
  tagline = 'Connecting bilingual talent with diverse career opportunities across industries'

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = 'tags'
  employer = 'employers'
